Repository F4ex/Weather4U, pull requests merged in 2024-05, with the labels that each got.

#4 Sinseunghyeon/add data
  .DS_Store
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/CategoryManager.swift
  Weather4U/Info.plist
  Weather4U/NetworkManager.swift
  Weather4U/ViewController.swift
  Weather4U/WeatherData.swift
Labels: Merge

#7 [Feat] 지역데이터 불러오기 구현 #3
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/JSONManager.swift
  Weather4U/LocationData.swift
  Weather4U/NetworkManager.swift
  Weather4U/ViewController.swift
  Weather4U/WeatherSentence.swift
  Weather4U/locationData.json
Labels: Merge

#12 새로운 기능 머지
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/CategoryManager.swift
  Weather4U/NetworkManager.swift
  Weather4U/ViewController.swift
  Weather4U/WeatherSentenceData.swift
  Weather4U/WeatherStatusData.swift
  Weather4U/WeatherTemperatureData.swift
  Weather4U/weatherLocationData.json
  Weather4U/weatherSentenceLocationData.json
  Weather4U/weatherStatusLocationData.json
  Weather4U/weatherTemperatureLocationData.json
Labels: Merge

#19 새로운 기능 추가
  Weather4U.xcodeproj/project.pbxproj
  Weather4U.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Weather4U.xcodeproj/xcuserdata/t2023-m0056.xcuserdatad/xcschemes/xcschememanagement.plist
  Weather4U/CategoryManager.swift
  Weather4U/MainWeather/ChartCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Merge

#23 데이터 받아오는 부분 수정 후 머지 부탁드립니다.
  Weather4U.xcodeproj/project.pbxproj
  Weather4U.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Weather4U.xcodeproj/xcuserdata/t2023-m0056.xcuserdatad/xcschemes/xcschememanagement.plist
  Weather4U/CategoryManager.swift
  Weather4U/LocationData.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/NetworkManager.swift
  Weather4U/ViewController.swift
  Weather4U/WeatherStatusData.swift
Labels: Merge

#27 [Merge] 초기 데이터 연결 추가 #3
  Weather4U/.DS_Store
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
  Weather4U/Managers/JSONManager.swift
  Weather4U/Managers/NetworkManager.swift
Labels: Merge

#28 머지요청합니다.
  Weather4U/AppDelegate.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/SceneDelegate.swift
Labels: Merge

#29 [tldhs27] search 기능 오류 수정
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/Managers/JSONManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/ModalViewController.swift
  Weather4U/MyWeather/SearchResultTableViewCell.swift
  Weather4U/MyWeather/SearchResultTableViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
Labels: Fix

#33 [tldhs27] 모달창 구현
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MyWeather/ModalViewController.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/MyWeatherPageViewController.swift
  Weather4U/MyWeather/SearchResultTableViewController.swift
Labels: Merge

#38 [tldhs27] 검색 정보 → 모달창에 연결
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/SearchResultTableViewCell.swift
  Weather4U/MyWeather/SearchResultTableViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
  Weather4U/Weather4U.xcdatamodeld/Weather4U.xcdatamodel/contents
Labels: Merge

#39 머지요청드립니다.
  Weather4U/MainWeather/CellModel.swift
  Weather4U/MainWeather/ChartCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CategoryManager.swift
  Weather4U/Managers/NetworkManager.swift
Labels: Merge

#42 머지 요청드립니다.
  Weather4U/.DS_Store
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CategoryManager.swift
Labels: Merge

#43 [tldhs27] 코어데이터 서울 첫번째로 저장
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/Managers/NetworkManager.swift
Labels: Add

#46 tldhs27] MyWeatherPage 셀 정보 설정
  Weather4U/MyWeather/FirstTableViewCell.swift
  Weather4U/MyWeather/MyWeatherPageTableViewCell.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Add

#49 [Feat] DispatchGroup을 활용해 데이터 받아오기 추가 후 머지 부탁드립니다.
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CategoryManager.swift
  Weather4U/Managers/NetworkManager.swift
Labels: Merge

#51 tldhs27] MyWeatherPage 오류 수정
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/MyWeatherPageViewController.swift
Labels: Add

#52 Sinseunghyeon/fix bug 머지 부탁드립니다.
  Weather4U/MainWeather/ChartCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/TodayWeatherCell.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
  Weather4U/Managers/CategoryManager.swift
Labels: Merge

#56 머지 부탁드립니다.
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/MainWeather/CellModel.swift
  Weather4U/MainWeather/ChartCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/WeatherStyle/StyleViewController.swift
Labels: Feature, Fix, Merge

#57 메인페이지 수정 요청한거 해결했습니당
  .DS_Store
  Weather4U/Assets.xcassets/Celsius.imageset/Contents.json
  Weather4U/Assets.xcassets/Celsius.imageset/mdi_temperature-celsius.svg
  Weather4U/Assets.xcassets/Fahrenheit.imageset/Contents.json
  Weather4U/Assets.xcassets/Fahrenheit.imageset/mdi_temperature-fahrenheit.svg
  Weather4U/Assets.xcassets/drop_Half.imageset/Contents.json
  Weather4U/Assets.xcassets/drop_Little.imageset/Contents.json
  Weather4U/Assets.xcassets/face/frown.imageset/Contents.json
  Weather4U/Assets.xcassets/face/frown.imageset/frownW.svg
  Weather4U/Assets.xcassets/face/laugh.imageset/Contents.json
  Weather4U/Assets.xcassets/face/laugh.imageset/smileW.svg
  Weather4U/Assets.xcassets/face/nah.imageset/Contents.json
  Weather4U/Assets.xcassets/face/nah.imageset/nahW.svg
  Weather4U/Assets.xcassets/face/smile.imageset/Contents.json
  Weather4U/Assets.xcassets/face/smile.imageset/laughW.svg
  Weather4U/Assets.xcassets/face/straightFace.imageset/Contents.json
  Weather4U/Assets.xcassets/face/straightFace.imageset/straightFaceW.svg
  Weather4U/MainWeather/FeelsCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/TodayWeatherCell.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
Labels: Design, Add, Merge

#59 [Feature]cell 클릭 시 modal 추가
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Feature

#60 시간별 날씨 헤더넣기, 셀 위치 수정
  .DS_Store
  Weather4U.xcodeproj/project.pbxproj
  Weather4U.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Weather4U/MainWeather/MainViewController.swift
Labels: Design, Add, Merge

#61 tldhs27] addButton, 셀 위치 이동
  .DS_Store
  Weather4U.xcodeproj/project.pbxproj
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/MyWeatherPageViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
Labels: Add

#62 Sinseunghyeon/bug fix 머지 부탁드립니다.
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/Managers/JSONManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Feature, Design, Fix, Add, Delete, Merge

#65 tableView modal 추가
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Feature, Add

#76 [Fix] TableView 오류 수정
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
Labels: Fix

#78 색상 날씨마다 변경
  Weather4U.xcodeproj/project.pbxproj
  Weather4U.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Weather4U/Assets.xcassets/drop_Half.imageset/Contents.json
  Weather4U/Assets.xcassets/drop_Half.imageset/drop_h.svg
  Weather4U/Assets.xcassets/drop_Little.imageset/Contents.json
  Weather4U/Assets.xcassets/drop_Little.imageset/drop_1:3.svg
  Weather4U/Assets.xcassets/face/frown.imageset/Contents.json
  Weather4U/Assets.xcassets/face/frown.imageset/frownW.svg
  Weather4U/Assets.xcassets/face/laugh.imageset/Contents.json
  Weather4U/Assets.xcassets/face/laugh.imageset/smileW.svg
  Weather4U/Assets.xcassets/face/nah.imageset/Contents.json
  Weather4U/Assets.xcassets/face/nah.imageset/nahW.svg
  Weather4U/Assets.xcassets/face/smile.imageset/Contents.json
  Weather4U/Assets.xcassets/face/smile.imageset/laughW.svg
  Weather4U/Assets.xcassets/face/straightFace.imageset/Contents.json
  Weather4U/Assets.xcassets/face/straightFace.imageset/straightFace.svg
  Weather4U/Assets.xcassets/face/straightFace.imageset/straightFaceW.svg
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
Labels: Merge

#77 [Fix] 버그나는 부분 예외처리 함
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/MyWeatherPageViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
Labels: Fix, Merge

#79 Develop to main
  .DS_Store
  Weather4U.xcodeproj/project.pbxproj
  Weather4U.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Weather4U/.DS_Store
  Weather4U/Assets.xcassets/drop_Half.imageset/Contents.json
  Weather4U/Assets.xcassets/drop_Half.imageset/drop_h.svg
  Weather4U/Assets.xcassets/drop_Little.imageset/Contents.json
  Weather4U/Assets.xcassets/drop_Little.imageset/drop_1:3.svg
  Weather4U/Assets.xcassets/face/frown.imageset/Contents.json
  Weather4U/Assets.xcassets/face/frown.imageset/frownW.svg
  Weather4U/Assets.xcassets/face/laugh.imageset/Contents.json
  Weather4U/Assets.xcassets/face/laugh.imageset/smileW.svg
  Weather4U/Assets.xcassets/face/nah.imageset/Contents.json
  Weather4U/Assets.xcassets/face/nah.imageset/nahW.svg
  Weather4U/Assets.xcassets/face/smile.imageset/Contents.json
  Weather4U/Assets.xcassets/face/smile.imageset/laughW.svg
  Weather4U/Assets.xcassets/face/straightFace.imageset/Contents.json
  Weather4U/Assets.xcassets/face/straightFace.imageset/straightFace.svg
  Weather4U/Assets.xcassets/face/straightFace.imageset/straightFaceW.svg
  Weather4U/MainWeather/ChartCollectionViewCell.swift
  Weather4U/MainWeather/MainViewController.swift
  Weather4U/MainWeather/TodayWeatherCell.swift
  Weather4U/MainWeather/WeekWeatherCell.swift
  Weather4U/Managers/CoreDataManager.swift
  Weather4U/Managers/DataProcessingManager.swift
  Weather4U/Managers/NetworkManager.swift
  Weather4U/MyWeather/MyWeatherPageTableViewController.swift
  Weather4U/MyWeather/MyWeatherPageViewController.swift
  Weather4U/MyWeather/SearchViewController.swift
Labels: Merge
